name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.5.2
      with:
        version: 14

    - name: make
      run: |
        clang --version
        clang src/main.cpp

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: "*"
